---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: 2482-EKS-Test-Cluster
  region: us-east-2
  version: "1.21"

fargateProfiles:
  - name: fp-dev
    selectors:
      # All workloads in the "default" Kubernetes namespace will be
      # scheduled onto Fargate:
      - namespace: default
      
  - name: fp-test
    selectors:
      # All workloads in the "dev" Kubernetes namespace matching the following
      # label selectors will be scheduled onto Fargate:
      - namespace: kube-system
